### PR TITLE
Updated API url to api.track.toggl.com

### PR DESCRIPTION
**Pull request by rzfzr**
As pointed out by #16, making sure the package keeps on working after June 2021 as by [this](https://github.com/toggl/toggl_api_docs)

---
This change is [Reviewable](https://reviewable.io/reviews/meedamian/toggl-cli/17)

### CODE REVIEW

**Comment by rzfzr** [comment]
What's up with the testing?

**Comment by NoobTW** [comment]
> warning Using the API from toggl.com or www.toggl.com will be dropped at The End of June 2021. Switch to api.track.toggl.com

**Comment by meeDamian** [comment]
Could you exclude formatting unrelated to the theme of this commit?

**Comment by rzfzr** [comment]
> Could you exclude formatting unrelated to the theme of this commit?

It seems @NoobTW was quicker at it, just accept #18 and we are good to go right?

**Pull request merged**
